package gocipher

import (
	"fmt"
	"testing"
)

func TestVigenere(t *testing.T) {
	text := "TKSYMWRJGHKBPTEIKCYRWXIELQUPSUTLLGYFIKYIAVFNRLQFKVVSMBMJOCZGILSEAPZRGCVVHTVQYKXJSHARVIPCOGHXGZCGLQNEEXLPDQVXWBLVKCTRSVXYWUORPNEJKVYBROGIQRABKZEGZAAJSMQRANLAGZCGLKVATZSUMEAFQICYSXLNPUSJLVORWIQVMULEMVXVJHHPIGIKGPLVWAITMTLJLQPVLJLBXPIIHGYZMBWVSXLFHZSGHKUTEKSDHCYVWWRTZCYGQICJMINRWBXYSVAJSXVFYTHZWPEMWUPZMTEIXGHGYZIJSNAUSCKYGPLUEAKRHKUTWMGLJKALLWPVKYOVPMXYWQAUIZHFWUUGEVIOHGYVIVGVVEYLTBSXJCWUIZGRFVLYPBLVVKMSIZIEUGZBGIRRLJPRJ"
	key, err := VigenereKey(text, 8)
	if err != nil {
		t.Error(key)
	}
	plain := VigenereDecrypt(text, key)
	fmt.Printf("key: %v\nplaintext: %s\n", key, plain)
}
